### ISSUE TITLE
Improve project documentation

### ISSUE THREAD

**Issue by dnuka** [dnuka/banda#1]
### Thank you for your interest in `banda`

this will guide you to create your first pull request 🥇 

first `fork` the repo and make a local copy for yourself to work on.
install the dependencies listed in the `requirements.txt`
run the program and get an idea about what is does. `python3 app.py`
star * the repo if you like the project :)
create a `git branch` to work on the README.md
use this branch to work on your changes. 
also create a branch in your `fork`(remote branch at GitHub) using the same local branch name.
then push your code in to that branch(remote branch at GitHub) `git push origin branch-name`
finally make your first pull request, add reference to this issue i.e Issue #1 in your pull request description.

#### README.md

right now there is nothing much in the  README.md 
your job is to add content to it like, `how to get started`, `license information`
or you could find any typos in rest of the code and fix them as your first pull request :)

Happy coding!

**Comment by jashgala** [comment]
Hi,
Are you also looking for contributions to the code?

**Comment by dnuka** [comment]
@jashgala sure! If you find something interesting, create an issue and then work on it :)

**Comment by asiedubrempong** [comment]
I would like to contribute by add a dependencies section to readme.md

**Comment by dnuka** [comment]
@asiedubrempong Go ahead :)

**Comment by asiedubrempong** [comment]
Thanks, I've made a PR
